Add -fgnu89-inline to CFLAGS
In GCC 5.1 default C standard changed to -std=gnu11. This changed behavior of
inline functions. Build error is:
[  102s] CMakeFiles/deviced.dir/src/display/core.c.o: In function `lcd_off_procedure':
[  102s] /home/abuild/rpmbuild/BUILD/deviced-1.0.0/src/display/core.c:797: undefined reference to `lcd_off_procedure'
[  104s] collect2: error: ld returned 1 exit status

Changing back to gnu89 inlining mode fixes the issue.

Also moved cmake command to %build section.

Change-Id: I796f9264945b81c039a0da77a94ea040aae5ac86
Signed-off-by: Yury Usishchev <y.usishchev@samsung.com>